---
title: "Data engineering assignment"
subtitle: 'MongoDB dataset code exports for the report'
author: "Kory"
output: word_document
date: "2024-03-24"
---

```{r setup, include=FALSE, echo=FALSE}
source(file=paste(getwd(),"/mongodb_dataset_code.R", sep="")) 
```

# Mongo DB dataset exports
```{r report_export_01, include=TRUE, echo=FALSE}
paste("number of missing values in entire dataset: ", export_01_0001, sep = "")
paste("is student_id a PK: ", !export_01_0002, sep = "")
paste("is class_id a PK: ", !export_01_0003, sep = "")
```

```{r report_export_02, include=TRUE, echo=FALSE}
export_02_0001
export_02_0002

paste("the range of scores (difference between the min and max scores): ", export_02_0003, sep = "")
```


```{r report_export_03, include=TRUE, echo=FALSE}
paste("mean: ", export_03_0001, sep = "")
paste("median: ", export_03_0002, sep = "")
paste("maximum: ", export_03_0003, sep = "")
paste("minimum: ", export_03_0004, sep = "")
paste("1st quartile: ", export_03_0005, sep = "")
paste("3rd quartile: ", export_03_0006, sep = "")
paste("standard deviation: ", export_03_0007, sep = "")
```

```{r report_export_04, include=TRUE, echo=FALSE}
export_04_0001
```


```{r report_export_05, include=TRUE, echo=FALSE, fig.width = 10}
export_05_0001
```



```{r report_export_06, include=TRUE, echo=FALSE}
export_06_0001
```


```{r report_export_07, include=TRUE, echo=FALSE}
export_07_0001
```









